/*
 * Motor_GPIO_Init.c
 *
 *  Created on: Nov 23, 2025
 *      Author: andrewvalles
 */

#include "main.h"
#include "Motor_GPIO_Init.h"

void Motor_GPIO_Init2(void) {
	//initialization code for the GPIO pins used for the Motors
	RCC->AHB2ENR   |=  (RCC_AHB2ENR_GPIODEN);
	GPIOD->MODER   &= ~(GPIO_MODER_MODE4 | GPIO_MODER_MODE5 | GPIO_MODER_MODE6 | GPIO_MODER_MODE7);
	GPIOD->MODER   |=  (GPIO_MODER_MODE4_0 | GPIO_MODER_MODE5_0 | GPIO_MODER_MODE6_0 | GPIO_MODER_MODE7_0);
	GPIOD->OTYPER  &= ~(GPIO_OTYPER_OT4 | GPIO_OTYPER_OT5 | GPIO_OTYPER_OT6 | GPIO_OTYPER_OT7);
	GPIOD->OSPEEDR |=  ((3 << GPIO_OSPEEDR_OSPEED4_Pos) | (3 << GPIO_OSPEEDR_OSPEED5_Pos) | (3 << GPIO_OSPEEDR_OSPEED6_Pos) | (3 << GPIO_OSPEEDR_OSPEED7_Pos));
	GPIOD->BRR = (GPIO_PIN_4 | GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7);
}

/*
void Motor_GPIO_Init1(void) {
	RCC->AHB2ENR   |=  (RCC_AHB2ENR_GPIOCEN);
	GPIOC->MODER   &= ~(GPIO_MODER_MODE8 | GPIO_MODER_MODE9 | GPIO_MODER_MODE10 | GPIO_MODER_MODE11);
	GPIOC->MODER   |=  (GPIO_MODER_MODE8_0 | GPIO_MODER_MODE9_0 | GPIO_MODER_MODE10_0 | GPIO_MODER_MODE11_0);
	GPIOC->OTYPER  &= ~(GPIO_OTYPER_OT8 | GPIO_OTYPER_OT9 | GPIO_OTYPER_OT10 | GPIO_OTYPER_OT11);
	GPIOC->OSPEEDR |=  ((3 << GPIO_OSPEEDR_OSPEED8_Pos) | (3 << GPIO_OSPEEDR_OSPEED9_Pos) | (3 << GPIO_OSPEEDR_OSPEED10_Pos) | (3 << GPIO_OSPEEDR_OSPEED11_Pos));
	GPIOC->BRR = (GPIO_PIN_8 | GPIO_PIN_9 | GPIO_PIN_10 | GPIO_PIN_11);
}
*/

/*
void Motor_GPIO_Init(void) {
	//initialization code for the GPIO pins used for the Motors
	RCC->AHB2ENR   |=  (RCC_AHB2ENR_GPIOBEN);
	GPIOF->MODER   &= ~(GPIO_MODER_MODE2 | GPIO_MODER_MODE6 | GPIO_MODER_MODE10 | GPIO_MODER_MODE11);
	GPIOF->MODER   |=  (GPIO_MODER_MODE2_0 | GPIO_MODER_MODE6_0 | GPIO_MODER_MODE10_0 | GPIO_MODER_MODE11_0);
	GPIOF->OTYPER  &= ~(GPIO_OTYPER_OT2 | GPIO_OTYPER_OT6 | GPIO_OTYPER_OT10 | GPIO_OTYPER_OT11);
	GPIOF->OSPEEDR |=  ((3 << GPIO_OSPEEDR_OSPEED2_Pos) | (3 << GPIO_OSPEEDR_OSPEED6_Pos) | (3 << GPIO_OSPEEDR_OSPEED10_Pos) | (3 << GPIO_OSPEEDR_OSPEED11_Pos));
	GPIOF->BRR = (GPIO_PIN_2 | GPIO_PIN_6 | GPIO_PIN_10 | GPIO_PIN_11);
}
*/
